run: test

test:
	@echo [ 17%]  Ready to compile.
	@echo [ 23%]  g++ -std=c++11 main.cpp Snake.cpp -o grade.out
	@g++ -std=c++11 main.cpp Snake.cpp -o grade.out
	@echo [ 70%]  Almost done.
	@echo [100%]  Cheers. Success! Built target grade.out.

clean:
	@echo [ 70%]  Cleaning objects.
	@rm -f grade.out
	@echo [100%] Done.